# Generated by Django 5.2 on 2025-06-19 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('visible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('best_practice', models.CharField(blank=True, max_length=100)),
                ('min_value', models.IntegerField(blank=True, null=True)),
                ('max_value', models.IntegerField(blank=True, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='params', to='policies.category')),
                ('config_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='policies.configtype')),
            ],
        ),
        migrations.CreateModel(
            name='ConfigSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_name', models.CharField(choices=[('prefix', 'prefix'), ('value', 'value'), ('suffix', 'suffix')], max_length=20)),
                ('default_text', models.TextField(blank=True)),
                ('is_value_slot', models.BooleanField(default=False)),
                ('position', models.PositiveSmallIntegerField()),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='policies.parameter')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('config_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='policies.configtype')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='policies.configsegment')),
            ],
        ),
    ]
