# Generated by Django 5.2 on 2025-06-19 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsegment',
            name='seg_name',
            field=models.CharField(choices=[('pt', 'Prefix/Suffix Text'), ('val', 'Value Slot')], max_length=10),
        ),
    ]
