# Generated by Django 5.2 on 2025-06-19 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0002_alter_configsegment_seg_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='visible',
        ),
    ]
