# Generated by Django 5.2 on 2025-06-20 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0003_remove_category_visible'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='value',
            name='segment',
        ),
    ]
