# Generated by Django 5.2 on 2025-06-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0004_remove_value_segment'),
    ]

    operations = [
        migrations.AddField(
            model_name='value',
            name='value_number',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configsegment',
            name='position',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
