# Generated by Django 5.2 on 2025-06-20 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0005_value_value_number_alter_configsegment_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='configsegment',
            name='line',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
