# Generated by Django 5.2 on 2025-06-23 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0006_configsegment_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsegment',
            name='seg_name',
            field=models.CharField(choices=[('pt', 'Text'), ('val', 'Value')], max_length=10),
        ),
        migrations.AlterField(
            model_name='value',
            name='value_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
