# Generated by Django 5.2 on 2025-06-25 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0007_alter_configsegment_seg_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('file_content', models.TextField()),
            ],
        ),
    ]
