# Generated by Django 5.2 on 2025-06-25 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0008_sessionrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SessionRecord',
        ),
    ]
