# Generated by Django 5.2 on 2025-06-25 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policies', '0010_session'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Session',
            new_name='SessionRecord',
        ),
    ]
